(() => {
const c=document.getElementById("game"),ctx=c.getContext("2d");ctx.imageSmoothingEnabled=false;
const W=c.width,H=c.height;
const C={bg:"#15141f",panel:"#0e1018",tile1:"#1a1620",tile2:"#241b28",gold:"#ffce4a",orange:"#f0a63a",darkOrange:"#8b4a22",text:"#fff3d0",muted:"#b9a88a",green:"#67e89a",cyan:"#52f0cf",red:"#ff5d55",deepRed:"#7a1f28",white:"#fff8df",black:"#090b11",fry:"#ffd15a",fry2:"#f19932",sauce:"#e84545",good:"#64f4a6",bad:"#2b1c20",rat:"#6d6a72",oil:"#ff9f2e",purple:"#8b5cf6"};
const keys=Object.create(null);
const LV=[
 {name:"LEVEL 1",order:"FRY STARTER",duration:38,spawn:.86,speed:118,bad:.14,gold:.03,goal:10},
 {name:"LEVEL 2",order:"SAUCE RUSH",duration:40,spawn:.72,speed:138,bad:.18,gold:.04,goal:12},
 {name:"LEVEL 3",order:"DOUBLE FRY",duration:42,spawn:.60,speed:158,bad:.22,gold:.05,goal:14},
 {name:"LEVEL 4",order:"NIGHT SHIFT",duration:44,spawn:.50,speed:178,bad:.25,gold:.06,goal:16},
 {name:"LEVEL 5",order:"GOLDEN FRY WAR",duration:46,spawn:.42,speed:200,bad:.28,gold:.08,goal:18},
 {name:"LEVEL 6",order:"COMBO COUNTER",duration:48,spawn:.38,speed:220,bad:.30,gold:.09,goal:20},
 {name:"LEVEL 7",order:"NEON FRY RUN",duration:50,spawn:.34,speed:238,bad:.32,gold:.10,goal:22},
 {name:"LEVEL 8",order:"KITCHEN STORM",duration:52,spawn:.31,speed:258,bad:.34,gold:.11,goal:24},
 {name:"LEVEL 9",order:"HOT OIL MAYHEM",duration:54,spawn:.28,speed:278,bad:.36,gold:.12,goal:26},
 {name:"LEVEL 10",order:"LEGENDARY FRY SHIFT",duration:58,spawn:.25,speed:302,bad:.38,gold:.14,goal:30}
];
const st={mode:"title",level:1,maxLevel:10,score:0,lives:3,combo:0,bestCombo:0,timer:45,lastTime:0,spawnTimer:0,boostCooldown:0,boostTime:0,message:"",result:null,runFinished:false,served:0,goal:10,daily:getDaily(),sparks:[]};
const p={x:360,y:545,w:92,h:26,speed:320};
const items=[];
function getDaily(){return{today:new Date().toDateString(),last:localStorage.getItem("mcmeal_fry_last_play"),streak:Number(localStorage.getItem("mcmeal_fry_streak")||"0")}}
function updateStreak(){const today=new Date().toDateString(),last=localStorage.getItem("mcmeal_fry_last_play");let s=Number(localStorage.getItem("mcmeal_fry_streak")||"0");if(last!==today){if(last){const d=Math.round((new Date(today)-new Date(last))/(86400000));s=d===1?s+1:1}else s=1;localStorage.setItem("mcmeal_fry_last_play",today);localStorage.setItem("mcmeal_fry_streak",String(s))}st.daily=getDaily()}
function reset(){st.mode="play";st.level=1;st.score=0;st.lives=4;st.combo=0;st.bestCombo=0;st.result=null;st.runFinished=false;setupLevel(1)}
function setupLevel(n){const d=LV[n-1];st.timer=d.duration;st.spawnTimer=.45;st.boostCooldown=0;st.boostTime=0;st.served=0;st.goal=d.goal;st.message=d.name+" started";p.x=W/2-p.w/2;items.length=0;st.sparks.length=0;setTimeout(()=>{if(st.mode==="play")st.message=""},850)}
function update(dt){if(st.mode!=="play")return;st.timer-=dt;st.spawnTimer-=dt;st.boostCooldown=Math.max(0,st.boostCooldown-dt);st.boostTime=Math.max(0,st.boostTime-dt);move(dt);spawn();updateItems(dt);updateSparks(dt);if(st.timer<=0||st.served>=st.goal)clearLevel()}
function move(dt){let dir=0;if(keys.ArrowLeft||keys.a)dir--;if(keys.ArrowRight||keys.d)dir++;const boost=st.boostTime>0?1.55:1;p.x+=dir*p.speed*boost*dt;p.x=Math.max(28,Math.min(W-p.w-28,p.x));if((keys.Space||keys[" "])&&st.boostCooldown<=0){st.boostTime=.65;st.boostCooldown=4;msg("Tray boost!");}}
function spawn(){const d=LV[st.level-1];if(st.spawnTimer>0)return;let type="fry",r=Math.random();if(r<d.gold)type="golden";else if(r<d.gold+d.bad)type=Math.random()<.55?"burnt":"rat";else if(r<.55)type="fry";else if(r<.78)type="sauce";else type="nugget";const size=(type==="rat"||type==="burnt")?38:32;const lane=40+Math.floor(Math.random()*8)*90+Math.random()*24;items.push({type,x:Math.max(28,Math.min(W-70,lane)),y:84,w:size,h:size,vy:d.speed+Math.random()*70+st.level*5,wobble:Math.random()*6.28,spin:Math.random()*6.28});st.spawnTimer=d.spawn*(.75+Math.random()*.55)}
function isGood(t){return["fry","sauce","nugget","golden"].includes(t)}
function updateItems(dt){for(let i=items.length-1;i>=0;i--){const it=items[i];it.y+=it.vy*dt;it.x+=Math.sin(it.y*.022+it.wobble)*.45;it.spin+=dt*3;if(hit(it,p)){collect(it);items.splice(i,1);continue}if(it.y>H-78){if(isGood(it.type)){st.combo=0;msg("Missed order!")}items.splice(i,1)}}}
function updateSparks(dt){for(let i=st.sparks.length-1;i>=0;i--){const s=st.sparks[i];s.life-=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.life<=0)st.sparks.splice(i,1)}}
function spark(x,y,col,n=8){for(let i=0;i<n;i++)st.sparks.push({x,y,vx:(Math.random()-.5)*120,vy:(Math.random()-.8)*130,life:.35+Math.random()*.25,col})}
function collect(it){if(isGood(it.type)){const pts=it.type==="golden"?520:it.type==="sauce"?170:it.type==="nugget"?140:110;st.combo++;st.bestCombo=Math.max(st.bestCombo,st.combo);st.served++;st.score+=pts+Math.min(700,st.combo*15);spark(it.x+16,it.y+16,it.type==="golden"?C.gold:C.green,9);if(it.type==="golden")msg("Golden fry! +520");else if(st.combo%8===0)msg(st.combo+" combo!");}else{st.lives--;st.combo=0;spark(it.x+16,it.y+16,C.red,14);msg(it.type==="rat"?"RAT ALERT! -1 life":"BURNT FOOD! -1 life");if(st.lives<=0)finish(false)}}
function msg(m){st.message=m;setTimeout(()=>{if(st.mode==="play"&&st.message===m)st.message=""},700)}
function clearLevel(){st.score+=st.level*650+st.combo*10;if(st.level<st.maxLevel){st.mode="levelclear";items.length=0}else finish(true)}
function nextLevel(){st.level++;setupLevel(st.level);st.mode="play"}
function postMCMealReward(){try{const r=st.result;if(!r||r._postedToHub)return;r._postedToHub=true;if(window.parent&&window.parent!==window){window.parent.postMessage({type:"MCMEAL_GAME_RESULT",game:"Fry Rush",score:r.score||st.score||0,won:!!r.won,levelsCleared:r.levelsCleared||st.level||1,rewards:r.rewards||{}},"*")}}catch(e){}}
function finish(won){if(st.runFinished)return;st.runFinished=true;updateStreak();st.result={won,score:st.score,levelsCleared:st.level,rewards:rewards(won)};st.mode="result";postMCMealReward();items.length=0}
function rewards(won){let fries=1,sauce=0,xp=25,ticket=0,frag=0;if(st.score>=1500){fries=2;xp=55}if(st.score>=4000){fries=4;sauce=1;xp=110;ticket=5}if(st.score>=8000){fries=6;sauce=2;xp=180;ticket=10;frag=1}xp+=(st.level-1)*30;ticket+=(st.level-1)*2;if(won){xp+=100;ticket+=3}const drops=[];for(let i=0;i<fries;i++)drops.push("Fries");for(let i=0;i<sauce;i++)drops.push("Sauce");if(st.bestCombo>=20)drops.push("Combo Spice");return{drops,xp,ticketChance:ticket,fragmentChance:frag,gotTicket:Math.random()*100<ticket,gotFragment:Math.random()*100<frag,streak:Number(localStorage.getItem("mcmeal_fry_streak")||"0"),bestCombo:st.bestCombo}}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function draw(){bg();if(st.mode==="title"){title();return}playfield();items.forEach(drawItem);drawPlayer();drawSparks();hud();orderZone();if(st.mode==="levelclear")levelClear();if(st.mode==="result")result()}
function bg(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#20142a");g.addColorStop(.5,"#11151d");g.addColorStop(1,"#0a090e");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="#100d12";ctx.fillRect(0,0,W,66)}
function playfield(){ctx.fillStyle="#0d1018";ctx.fillRect(0,66,W,510);for(let y=80;y<570;y+=38)for(let x=0;x<W;x+=52){ctx.fillStyle=(x+y)%104===0?C.tile1:C.tile2;ctx.fillRect(x,y,48,34)}ctx.fillStyle="#2c1720";ctx.fillRect(0,96,W,34);ctx.fillStyle=C.orange;ctx.fillRect(70,112,W-140,14);ctx.fillStyle=C.darkOrange;ctx.fillRect(70,126,W-140,8);for(let x=86;x<W-80;x+=42){ctx.fillStyle="#ffd066";ctx.fillRect(x,115,20,3)}ctx.fillStyle=C.black;ctx.fillRect(0,575,W,85);ctx.fillStyle=C.darkOrange;ctx.fillRect(0,575,W,8);ctx.fillStyle="#361d16";ctx.fillRect(0,605,W,55)}
function hud(){const d=LV[st.level-1];ctx.fillStyle="#100d12";ctx.fillRect(0,0,W,66);ctx.fillStyle=C.gold;ctx.font="22px Courier New";ctx.fillText("MC MEAL: FRY RUSH",20,26);ctx.fillStyle=C.text;ctx.font="18px Courier New";ctx.fillText(`Score ${st.score}`,20,54);ctx.fillText(`Lives ${st.lives}`,150,54);ctx.fillText(`Level ${st.level}/${st.maxLevel}`,260,54);ctx.fillText(`Time ${Math.ceil(st.timer)}s`,410,54);ctx.fillText(`Served ${st.served}/${st.goal}`,545,54);ctx.fillText(`Combo ${st.combo}`,680,54);if(st.message){ctx.fillStyle=C.green;ctx.font="16px Courier New";ctx.fillText(st.message,500,26)}ctx.fillStyle=C.white;ctx.font="13px Courier New";ctx.fillText(d.order,20,86)}
function title(){txt("MC MEAL",210,130,54,C.gold,"#74311f");txt("FRY RUSH",225,205,42,C.white,"#74311f");fryBox(352,274,2.3);panel(135,374,530,176);drawWrapped(["Catch fries, sauce and golden drops.","Avoid clearly marked burnt food and rats.","10 levels with faster lanes, combos and kitchen chaos.","Press ENTER or tap canvas to start"],170,418,460,28,19,C.text)}
function orderZone(){panel(240,588,320,58);ctx.fillStyle=C.gold;ctx.font="14px Courier New";centerText("ORDER TRAY",400,610);ctx.fillStyle=C.text;ctx.font="12px Courier New";centerText("Catch GOOD food only",400,632);centerText("Red X / rats = avoid",400,647)}
function drawPlayer(){ctx.fillStyle=st.boostTime>0?C.cyan:C.orange;ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle=C.darkOrange;ctx.fillRect(p.x+8,p.y+p.h-7,p.w-16,7);ctx.fillStyle=C.white;ctx.fillRect(p.x+12,p.y+5,p.w-24,4);ctx.fillStyle="#6f351e";ctx.fillRect(p.x+p.w/2-5,p.y+p.h,10,18)}
function drawItem(it){if(it.type==="fry")fry(it.x,it.y,1.15);else if(it.type==="golden"){fry(it.x,it.y,1.15);ctx.fillStyle=C.gold;ctx.fillRect(it.x-2,it.y-2,8,8);ctx.fillStyle=C.white;ctx.fillRect(it.x+4,it.y+2,5,3)}else if(it.type==="sauce")sauce(it.x,it.y,1.15);else if(it.type==="nugget")nugget(it.x,it.y,1.15);else if(it.type==="burnt")burnt(it.x,it.y,1.2);else rat(it.x,it.y,1.15)}
function fry(x,y,s){const u=4*s;ctx.fillStyle=C.fry;ctx.fillRect(x+2*u,y,3*u,8*u);ctx.fillRect(x+5*u,y+u,3*u,8*u);ctx.fillRect(x+8*u,y-u,3*u,9*u);ctx.fillStyle=C.fry2;ctx.fillRect(x+2*u,y+7*u,9*u,2*u);ctx.fillStyle=C.good;ctx.fillRect(x+12*u,y+2*u,3*u,3*u)}
function sauce(x,y,s){const u=4*s;ctx.fillStyle=C.sauce;ctx.fillRect(x+u,y+2*u,7*u,7*u);ctx.fillStyle=C.white;ctx.fillRect(x+2*u,y+u,5*u,2*u);ctx.fillStyle=C.good;ctx.fillRect(x+8*u,y+2*u,3*u,3*u)}
function nugget(x,y,s){const u=4*s;ctx.fillStyle="#d98b3a";ctx.fillRect(x+u,y+2*u,8*u,5*u);ctx.fillStyle="#f2bc62";ctx.fillRect(x+2*u,y+2*u,5*u,2*u);ctx.fillStyle=C.good;ctx.fillRect(x+9*u,y+u,3*u,3*u)}
function burnt(x,y,s){const u=4*s;ctx.fillStyle="#171217";ctx.fillRect(x+u,y+2*u,8*u,6*u);ctx.fillStyle=C.deepRed;ctx.fillRect(x+2*u,y+3*u,6*u,4*u);ctx.strokeStyle=C.red;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x+u,y+u);ctx.lineTo(x+10*u,y+10*u);ctx.moveTo(x+10*u,y+u);ctx.lineTo(x+u,y+10*u);ctx.stroke()}
function rat(x,y,s){const u=4*s;ctx.fillStyle=C.rat;ctx.fillRect(x+u,y+3*u,8*u,4*u);ctx.fillRect(x+6*u,y+2*u,4*u,3*u);ctx.fillStyle=C.red;ctx.fillRect(x+8*u,y+3*u,u,u);ctx.fillStyle=C.white;ctx.fillRect(x+9*u,y+6*u,3*u,2*u);ctx.strokeStyle=C.red;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+u,y+u);ctx.lineTo(x+10*u,y+10*u);ctx.moveTo(x+10*u,y+u);ctx.lineTo(x+u,y+10*u);ctx.stroke()}
function fryBox(x,y,s){const u=4*s;ctx.fillStyle=C.deepRed;ctx.fillRect(x+2*u,y+8*u,16*u,13*u);ctx.fillStyle=C.red;ctx.fillRect(x+3*u,y+9*u,14*u,11*u);for(let i=0;i<7;i++){ctx.fillStyle=C.fry;ctx.fillRect(x+(4+i*2)*u,y+(i%2)*u,1.2*u,10*u)}ctx.fillStyle=C.gold;ctx.font=`${11*s}px Courier New`;ctx.fillText("M",x+7*u,y+17*u)}
function drawSparks(){st.sparks.forEach(s=>{ctx.globalAlpha=Math.max(0,s.life*3);ctx.fillStyle=s.col;ctx.fillRect(s.x,s.y,4,4);ctx.globalAlpha=1})}
function levelClear(){const next=Math.min(st.level+1,st.maxLevel);panel(110,190,580,218);ctx.fillStyle=C.green;ctx.font="30px Courier New";centerText(`${LV[st.level-1].name} COMPLETE!`,400,235);ctx.fillStyle=C.text;ctx.font="18px Courier New";centerText(`Score Bonus Added: ${st.level*650}`,400,282);centerText(`Next Order: ${LV[next-1].order}`,400,314);centerText("More drops. Clearer danger. Faster kitchen.",400,346);centerText("Press ENTER / Tap for next level",400,378)}
function result(){panel(90,80,620,470);const r=st.result;ctx.fillStyle=r.won?C.green:C.red;ctx.font="34px Courier New";centerText(r.won?"FRY SHIFT COMPLETE!":"KITCHEN CLOSED!",400,132);ctx.fillStyle=C.text;ctx.font="20px Courier New";ctx.fillText(`Final Score: ${r.score}`,160,178);ctx.fillText(`Levels Cleared: ${r.levelsCleared}/${st.maxLevel}`,160,208);ctx.fillText(`Best Combo: ${r.rewards.bestCombo}`,160,238);ctx.fillText(`XP Earned: ${r.rewards.xp}`,160,268);ctx.fillText(`Daily Streak: ${r.rewards.streak}`,160,298);ctx.fillStyle=C.gold;ctx.fillText("Ingredient Drops:",160,340);ctx.fillStyle=C.text;ctx.font="18px Courier New";const lines=wrap(r.rewards.drops.join(", "),390);let y=370;lines.forEach(line=>{ctx.fillText(line,160,y);y+=24});y+=10;if(r.rewards.gotTicket){ctx.fillStyle=C.green;ctx.fillText("Bonus: Mystery Ticket!",160,y);y+=28}else{ctx.fillStyle=C.muted;ctx.fillText(`Ticket chance rolled: ${r.rewards.ticketChance}%`,160,y);y+=28}if(r.rewards.gotFragment){ctx.fillStyle=C.green;ctx.fillText("Ultra Bonus: Recipe Fragment!",160,y);y+=28}ctx.fillStyle=C.white;ctx.font="18px Courier New";ctx.fillText("Press ENTER / Tap to play again",160,520)}
function panel(x,y,w,h){ctx.fillStyle="#0f1118";ctx.fillRect(x,y,w,h);ctx.strokeStyle=C.orange;ctx.lineWidth=4;ctx.strokeRect(x,y,w,h);ctx.strokeStyle=C.darkOrange;ctx.lineWidth=2;ctx.strokeRect(x+8,y+8,w-16,h-16)}
function centerText(t,x,y){ctx.fillText(t,x-ctx.measureText(t).width/2,y)}
function wrap(text,max){const words=String(text||"").split(/\s+/),lines=[];let line="";for(const w of words){const t=line?line+" "+w:w;if(ctx.measureText(t).width<=max)line=t;else{if(line)lines.push(line);line=w}}if(line)lines.push(line);return lines}
function drawWrapped(lines,x,y,max,lineH,fontSize,col){ctx.fillStyle=col;ctx.font=`${fontSize}px Courier New`;let yy=y;lines.forEach(t=>{wrap(t,max).forEach(l=>{ctx.fillText(l,x,yy);yy+=lineH})})}
function txt(t,x,y,s,col,sh){ctx.font=`${s}px Courier New`;ctx.fillStyle=sh;ctx.fillText(t,x+4,y+4);ctx.fillStyle=col;ctx.fillText(t,x,y)}
function loop(t){const dt=Math.min(.033,(t-st.lastTime)/1000||0);st.lastTime=t;update(dt);draw();requestAnimationFrame(loop)}
function action(){if(st.mode==="title"||st.mode==="result")reset();else if(st.mode==="levelclear")nextLevel()}
window.addEventListener("keydown",e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;keys[k]=true;if(e.key==="Enter")action();if(["ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault()});
window.addEventListener("keyup",e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;keys[k]=false});
c.addEventListener("pointerdown",()=>action());
document.querySelectorAll("[data-key]").forEach(b=>{const k=b.getAttribute("data-key");const down=e=>{e.preventDefault();keys[k]=true;if(k==="Space")keys[" "]=true};const up=e=>{e.preventDefault();keys[k]=false;if(k==="Space")keys[" "]=false};b.addEventListener("pointerdown",down);b.addEventListener("pointerup",up);b.addEventListener("pointerleave",up);b.addEventListener("pointercancel",up)});
requestAnimationFrame(loop);
})();
